- hosts: all
  become: true
  # gather_facts: false


  roles:
    # - { role: users } #need work 
    - { role: nginx, tags: ["nginx"] }
    - { role: mysql_server, tags: ["mysql"] }
    - { role: php, tags: ["php"] }
    - { role: iptables, tags: ["iptables"] } 


