---
# tasks file for mysql_server
- name: Install ansible python3 mysql dependency
  apt:
    name: python3-mysqldb
    state: latest

- name: install mysql packages 
  apt: 
    name: 
      - mysql-server
    state: present
    update_cache: yes
  notify:
    - start mysql service 

- name: create databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
    target: "{{ item.target | default(omit) }}"
  with_items: "{{ mysql_databases }}"


- name: create users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: False 
